//! `ledger init` project scaffolding.
// ledger-lint:allow (host application; init writes template files on disk,
//   unlike simulation code)

use std::collections::BTreeMap;
use std::fmt;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use ledger_format::{MANIFEST_FORMAT_VERSION, RunManifest};

#[derive(Debug)]
pub enum ScaffoldError {
    CreateDir {
        path: PathBuf,
        error: io::Error,
    },
    Write {
        path: PathBuf,
        error: io::Error,
    },
    /// `repro.ldgr` exists and `--force` was not given.
    RefuseOverwrite(PathBuf),
    /// The default manifest could not be canonically encoded.
    Manifest(String),
}

impl fmt::Display for ScaffoldError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::CreateDir { path, error } => {
                write!(formatter, "cannot create {}: {error}", path.display())
            }
            Self::Write { path, error } => {
                write!(formatter, "cannot write {}: {error}", path.display())
            }
            Self::RefuseOverwrite(path) => write!(
                formatter,
                "refusing to overwrite existing {} (use --force)",
                path.display()
            ),
            Self::Manifest(detail) => write!(formatter, "cannot encode default manifest: {detail}"),
        }
    }
}

impl std::error::Error for ScaffoldError {}

#[derive(Debug)]
pub struct ScaffoldReport {
    pub dir: PathBuf,
    pub created: Vec<PathBuf>,
    /// Existing files left untouched because `--force` was not given.
    pub skipped: Vec<PathBuf>,
}

/// Scaffolds a project template into `dir`.
///
/// Refuses to overwrite an existing `repro.ldgr` unless `force` is true.
/// Other existing files are skipped and reported when `force` is false.
pub fn scaffold(dir: &Path, force: bool) -> Result<ScaffoldReport, ScaffoldError> {
    fs::create_dir_all(dir).map_err(|error| ScaffoldError::CreateDir {
        path: dir.to_path_buf(),
        error,
    })?;

    let src_dir = dir.join("src");
    fs::create_dir_all(&src_dir).map_err(|error| ScaffoldError::CreateDir {
        path: src_dir.clone(),
        error,
    })?;

    let mut report = ScaffoldReport {
        dir: dir.to_path_buf(),
        created: Vec::new(),
        skipped: Vec::new(),
    };

    write_file(
        dir,
        "repro.ldgr",
        default_manifest()?.as_slice(),
        force,
        &mut report,
    )?;
    write_file(
        dir,
        "README.md",
        README_TEMPLATE.as_bytes(),
        force,
        &mut report,
    )?;
    write_file(
        dir,
        "AGENTS.md",
        AGENTS_TEMPLATE.as_bytes(),
        force,
        &mut report,
    )?;
    write_file(
        &src_dir,
        "main.rs",
        MAIN_RS_TEMPLATE.as_bytes(),
        force,
        &mut report,
    )?;

    Ok(report)
}

fn write_file(
    dir: &Path,
    name: &str,
    bytes: &[u8],
    force: bool,
    report: &mut ScaffoldReport,
) -> Result<(), ScaffoldError> {
    let path = dir.join(name);
    if path.exists() && !force {
        if name == "repro.ldgr" {
            return Err(ScaffoldError::RefuseOverwrite(path));
        }
        report.skipped.push(path);
        return Ok(());
    }
    fs::write(&path, bytes).map_err(|error| ScaffoldError::Write {
        path: path.clone(),
        error,
    })?;
    report.created.push(path);
    Ok(())
}

fn default_manifest() -> Result<Vec<u8>, ScaffoldError> {
    let manifest = RunManifest {
        format_version: MANIFEST_FORMAT_VERSION,
        root_seed: [0u8; 32],
        policy_tag: "bandit".into(),
        journal_root: [0u8; 32],
        entry_count: 0,
        actor_heads: BTreeMap::new(),
        extensions: BTreeMap::new(),
    };
    manifest
        .to_canonical_bytes()
        .map_err(|error| ScaffoldError::Manifest(error.to_string()))
}

/// Reference simulation program written into `src/main.rs`.
const MAIN_RS_TEMPLATE: &str = r#"//! Two-task Send/Receive reference simulation.
//!
//! Generated by `ledger init`. This program compiles against the workspace
//! when your crate depends on ledger-sim, ledger-explorer, and ledger-format.
//! Run it with: `cargo run -p <your-crate> -- <seed>`.

use ledger_explorer::search::{Workload, search};
use ledger_explorer::{HistoryOracle, KeyValueSpec, solve_ldfi};
use ledger_format::{EntryKind, Payload};
use ledger_sim::{Instruction, Policy, RunConfig, RunResult};

/// Two-task workload: task 0 sends value 42 to task 1, task 1 receives it.
struct TwoTask;

impl Workload for TwoTask {
    fn programs(&self) -> Vec<Vec<Instruction>> {
        vec![
            vec![
                Instruction::Send { to: 1, payload: 42 },
                Instruction::Done,
            ],
            vec![
                Instruction::Receive,
                Instruction::Outcome,
                Instruction::Done,
            ],
        ]
    }

    fn history(&self, run: &RunResult) -> Vec<ledger_explorer::HistoryOperation> {
        run.journal
            .entries()
            .filter_map(|entry| match (&entry.data.kind, &entry.data.payload) {
                (EntryKind::Send, Payload::Pair { left: 1, right: 42 }) => {
                    Some(ledger_explorer::HistoryOperation::Write {
                        key: "k".into(),
                        value: 42,
                        witness: entry.id,
                    })
                }
                (EntryKind::Outcome, Payload::Number(value)) => {
                    Some(ledger_explorer::HistoryOperation::Read {
                        key: "k".into(),
                        value: *value,
                        witness: entry.id,
                    })
                }
                _ => None,
            })
            .collect()
    }
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut seed = [0u8; 32];
    if let Some(arg) = std::env::args().nth(1) {
        if let Ok(value) = arg.parse::<u64>() {
            seed[..8].copy_from_slice(&value.to_le_bytes());
        }
    }
    let config = RunConfig {
        seed,
        policy: Policy::Bandit {
            exploration_constant: 1.414,
            pct_mix: 0.1,
        },
        max_steps: 256,
        ..RunConfig::default()
    };
    let workload = TwoTask;
    let oracle = HistoryOracle::new(&workload, KeyValueSpec::default());
    if let Some(finding) = search(&workload, &oracle, config, 100)? {
        println!("Violation detected: {}", finding.verdict.reason);
        println!("Journal root: {:02x?}", finding.run.journal.root_hash());
        let hypotheses = solve_ldfi(&finding.run.journal, &finding.verdict);
        println!("LDFI hypotheses: {}", hypotheses.len());
    } else {
        println!("Simulation passed (100 runs evaluated).");
    }
    Ok(())
}
"#;

/// Short project description written into `README.md`.
const README_TEMPLATE: &str = r#"# <project>

Generated by `ledger init`.

A deterministic simulation project for the Ledger DST platform. The run
manifest `repro.ldgr` pins the root seed, scheduling policy, and journal root
of a reproducible trial. See `docs/` in the ledger workspace for the format
and workflow documentation.

Build and run:

```sh
cargo run -- <seed>
```
"#;

/// Determinism rules copied into `AGENTS.md`.
const AGENTS_TEMPLATE: &str = r#"# AGENTS.md - Determinism rules for this simulation project

When authoring simulations, follow these rules. They mirror the ledger
workspace rules and keep every run reproducible.

1. Never read the ambient wall clock. Use `VirtualTime` or `Effects::now_ticks()`.
2. Never invoke ambient random generators. Derive streams via `SeedTree::rng(label)`.
3. Never spawn OS threads. Use cooperative tasks via `Simulation::with_tasks`
   and `Boundary::spawn_task`.
4. Never perform raw file I/O. Route file access through `SimFs`.
5. Never perform raw network I/O. Route messages through `SimNet`.

Run the workspace linter (`cargo run -p ledger-lint -- crates/`) before
merging changes.
"#;

#[cfg(test)]
mod tests {
    use super::{AGENTS_TEMPLATE, MAIN_RS_TEMPLATE};

    #[test]
    fn main_template_reads_optional_seed_from_argv() {
        assert!(
            MAIN_RS_TEMPLATE.contains("std::env::args().nth(1)"),
            "generated main must read an optional seed from argv"
        );
        assert!(
            MAIN_RS_TEMPLATE.contains("[0u8; 32]"),
            "generated main must fall back to the zero seed"
        );
        assert!(
            MAIN_RS_TEMPLATE.contains("let mut seed"),
            "generated seed must be mutable to accept argv"
        );
    }

    #[test]
    fn agents_template_uses_workspace_lint_command() {
        assert!(
            AGENTS_TEMPLATE.contains("cargo run -p ledger-lint -- crates/"),
            "AGENTS.md must reference the workspace linter command"
        );
        assert!(
            !AGENTS_TEMPLATE.contains("ledger lint"),
            "AGENTS.md must not reference the nonexistent `ledger lint` subcommand"
        );
    }
}
