#![cfg(feature = "std")]
//! Byte-equality proofs for the batch append path.
//!
//! The contract under test: [`Journal::append_batch`] produces ids, vector
//! clocks, parents, and root hashes byte-identical to looping
//! [`Journal::append`] over the same operation sequence.

use proptest::prelude::*;

use ledger_format::{ActorId, CborValue, EntryKind, Hash, Payload};
use ledger_journal::{BatchEntry, Journal};

/// One journal operation generated by the property strategies.
///
/// `observed_refs` names earlier emitted entries by back-distance; resolved
/// at run time against the sequential run's ids so both runs receive
/// identical observed-parent inputs.
#[derive(Debug, Clone)]
struct Op {
    kind: OpKind,
    actor: ActorId,
    observed_refs: Vec<usize>,
    chain_previous: bool,
    payload: Payload,
}

#[derive(Debug, Clone, Copy)]
enum OpKind {
    Outcome,
    TimerSet,
    Send,
    RngDraw(u32),
    InputStep { generator: u64, replay: u64 },
    Partition { src: ActorId, dst: ActorId },
}

impl OpKind {
    fn into_kind(self) -> EntryKind {
        match self {
            Self::Outcome => EntryKind::Outcome,
            Self::TimerSet => EntryKind::TimerSet,
            Self::Send => EntryKind::Send,
            Self::RngDraw(stream) => EntryKind::RngDraw { stream },
            Self::InputStep { generator, replay } => EntryKind::InputStep { generator, replay },
            Self::Partition { src, dst } => EntryKind::Fault {
                fault: ledger_format::FaultSpec::Partition { src, dst },
            },
        }
    }
}

fn resolve_refs(op: &Op, ids: &[Hash]) -> Vec<Hash> {
    op.observed_refs
        .iter()
        .filter_map(|back| {
            back.checked_sub(1)
                .and_then(|index| ids.get(index).copied())
        })
        .collect()
}

fn apply_sequential(journal: &mut Journal, ops: &[Op]) -> Vec<Hash> {
    let mut ids = Vec::with_capacity(ops.len());
    for op in ops {
        let mut observed = resolve_refs(op, &ids);
        if op.chain_previous {
            // `chain_previous` means "the immediately previous id is also an
            // observed parent"; append it last so both runs receive the same
            // parent list, dedup included.
            if let Some(previous) = ids.last().copied()
                && !observed.contains(&previous)
            {
                observed.push(previous);
            }
        }
        ids.push(
            journal
                .append(op.kind.into_kind(), op.actor, observed, op.payload.clone())
                .unwrap(),
        );
    }
    ids
}

/// One generated operation tuple, as produced by the property strategies.
/// Shared so every partition-shape test generates the identical op space.
type OpTuple = (u8, u32, Vec<usize>, bool, u8, Option<u64>);

/// Map one generated operation tuple into an [`Op`], shared by every
/// property test so the op space stays identical across partition shapes.
fn generate_ops(ops: Vec<OpTuple>) -> Vec<Op> {
    ops.into_iter()
        .map(|(kind_tag, actor, refs, chain, payload_tag, extra)| Op {
            kind: match kind_tag {
                0 => OpKind::Outcome,
                1 => OpKind::TimerSet,
                2 => OpKind::Send,
                3 => OpKind::RngDraw((extra.unwrap_or(0) % 7) as u32),
                4 => OpKind::InputStep {
                    generator: extra.unwrap_or(0),
                    replay: extra.unwrap_or(0).wrapping_mul(31),
                },
                _ => OpKind::Partition {
                    src: actor,
                    dst: (actor % 3) + 1,
                },
            },
            actor,
            observed_refs: refs,
            chain_previous: chain,
            payload: match payload_tag {
                0 => Payload::Empty,
                1 => Payload::Number(extra.unwrap_or(0)),
                2 => Payload::Signed(-(extra.unwrap_or(0) as i64)),
                3 => Payload::Text(format!("p-{}", extra.unwrap_or(0))),
                4 => Payload::Pair {
                    left: extra.unwrap_or(0),
                    right: extra.unwrap_or(0).wrapping_mul(7),
                },
                _ => Payload::Bytes(vec![payload_tag; 8 + (extra.unwrap_or(0) % 16) as usize]),
            },
        })
        .collect()
}

/// Apply `ops` through [`Journal::append_batch`] partitioned by the given
/// per-batch sizes (cycled), against the ids of the sequential run.
///
/// `chain_previous` inside a batch uses the batch's chained flag; across a
/// batch boundary the previous op's id is an ordinary observed parent, so
/// the two runs resolve identical parent lists regardless of the partition
/// shape.
fn apply_batched_partitioned(
    journal: &mut Journal,
    ops: &[Op],
    sequential_ids: &[Hash],
    sizes: &[usize],
) -> Vec<Hash> {
    let mut ids = Vec::with_capacity(ops.len());
    let mut base = 0usize;
    let mut size_index = 0usize;
    while base < ops.len() {
        let size = sizes[size_index % sizes.len()].max(1);
        let end = (base + size).min(ops.len());
        let batch = ops[base..end]
            .iter()
            .enumerate()
            .map(|(position, op)| {
                // Observed parents known up front resolve against the
                // sequential run's ids. `chain_previous` names the previous
                // OP; inside this batch that id resolves at append time via
                // the chained flag, across a batch boundary it is just an
                // ordinary observed parent.
                let global_index = base + position;
                let mut entry = BatchEntry::new(op.kind.into_kind(), op.actor, op.payload.clone());
                // Same visibility rule as the sequential run: a reference
                // resolves only against entries already appended.
                let visible = &sequential_ids[..global_index.min(sequential_ids.len())];
                for parent in resolve_refs(op, visible) {
                    entry.observed_parents.push(parent);
                }
                if op.chain_previous && global_index > 0 {
                    if position > 0 {
                        entry.chain_previous = true;
                    } else {
                        entry
                            .observed_parents
                            .push(sequential_ids[global_index - 1]);
                    }
                }
                entry
            })
            .collect::<Vec<_>>();
        ids.extend(journal.append_batch(batch).unwrap());
        base = end;
        size_index += 1;
    }
    ids
}

fn apply_batched(
    journal: &mut Journal,
    ops: &[Op],
    sequential_ids: &[Hash],
    chunk_size: usize,
) -> Vec<Hash> {
    apply_batched_partitioned(journal, ops, sequential_ids, &[chunk_size.max(1)])
}

fn assert_journals_identical(left: &Journal, right: &Journal) {
    assert_eq!(left.len(), right.len(), "entry counts must match");
    assert_eq!(
        left.root_hash(),
        right.root_hash(),
        "root hashes must be byte-identical"
    );
    let (mut a, mut b) = (left.entries(), right.entries());
    loop {
        match (a.next(), b.next()) {
            (Some(x), Some(y)) => {
                assert_eq!(x.id, y.id, "entry id mismatch in append order");
                assert_eq!(x.data, y.data, "entry data mismatch in append order");
                assert_eq!(
                    x.vector_clock, y.vector_clock,
                    "vector clock mismatch in append order"
                );
            }
            (None, None) => break,
            _ => panic!("journals diverge in length despite equal len()"),
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(256))]

    #[test]
    fn batch_appends_are_byte_identical_to_loop_append(
        ops in prop::collection::vec(
            (
                0u8..6,
                1u32..4,
                prop::collection::vec(1usize..8, 0..2),
                prop::bool::ANY,
                0u8..5,
                prop::option::of(0u64..1_000),
            ),
            0..120,
        )
    ) {
        let mut seq = Journal::new();
        let mut bat = Journal::new();
        let ops = generate_ops(ops);

        let sequential_ids = apply_sequential(&mut seq, &ops);
        let chunk_size = 1 + (ops.len() % 5);
        let batched_ids = apply_batched(&mut bat, &ops, &sequential_ids, chunk_size);
        prop_assert_eq!(sequential_ids, batched_ids);
        assert_journals_identical(&seq, &bat);
    }

    /// INDEPENDENT ARBITRARY PARTITIONS: the same randomized operation
    /// sequence partitioned into batches of arbitrary mixed sizes (1..=7,
    /// cycled) must produce byte-identical ids, entries, vector clocks, and
    /// journal roots against the per-entry append run. This covers partition
    /// shapes the fixed 1/N and N/1 legs cannot: interior boundaries, size
    /// one runs, and size bursts crossing observe/chain boundaries.
    #[test]
    fn arbitrary_batch_partitions_are_byte_identical_to_loop_append(
        ops in prop::collection::vec(
            (
                0u8..6,
                1u32..4,
                prop::collection::vec(1usize..8, 0..2),
                prop::bool::ANY,
                0u8..5,
                prop::option::of(0u64..1_000),
            ),
            0..120,
        ),
        sizes in prop::collection::vec(1usize..=7, 1..32),
    ) {
        let mut seq = Journal::new();
        let mut bat = Journal::new();
        let ops = generate_ops(ops);
        prop_assert!(!sizes.is_empty(), "the partition plan must be non-empty");

        let sequential_ids = apply_sequential(&mut seq, &ops);
        let batched_ids = apply_batched_partitioned(&mut bat, &ops, &sequential_ids, &sizes);
        prop_assert_eq!(sequential_ids, batched_ids);
        assert_journals_identical(&seq, &bat);
    }
}

#[test]
fn single_entry_batches_match_append_for_every_shape() {
    let shapes: Vec<(EntryKind, Payload)> = vec![
        (EntryKind::Outcome, Payload::Empty),
        (EntryKind::TimerSet, Payload::Number(9_000)),
        (EntryKind::Send, Payload::Pair { left: 2, right: 77 }),
        (EntryKind::RngDraw { stream: 3 }, Payload::Number(1 << 40)),
        (
            EntryKind::InputStep {
                generator: 12,
                replay: 34,
            },
            Payload::Text("step".into()),
        ),
        (
            EntryKind::Fault {
                fault: ledger_format::FaultSpec::Partition { src: 1, dst: 2 },
            },
            Payload::Bytes(vec![0xaa; 40]),
        ),
        (EntryKind::Assert, Payload::Signed(-123)),
    ];

    let mut sequential = Journal::new();
    let mut batched = Journal::new();
    for (kind, payload) in &shapes {
        let actor = 1;
        let parent = sequential.head_for_actor(actor);
        let expected = sequential
            .append(*kind, actor, parent, payload.clone())
            .unwrap();
        let batch = vec![BatchEntry::new(*kind, actor, payload.clone())];
        let got = batched.append_batch(batch).unwrap();
        assert_eq!(got, vec![expected]);
    }
    assert_journals_identical(&sequential, &batched);
}

#[test]
fn batches_crossing_the_freeze_threshold_stay_identical() {
    let total = OVERLAY_CROSSING_ENTRIES;
    let ops: Vec<(EntryKind, Payload)> = (0..total as u64)
        .map(|i| {
            (
                if i % 2 == 0 {
                    EntryKind::Outcome
                } else {
                    EntryKind::Send
                },
                Payload::Number(i),
            )
        })
        .collect();

    // Exclusive base: freezes run at every threshold crossing.
    let mut sequential = Journal::new();
    let mut batched = Journal::new();
    for (kind, payload) in &ops {
        sequential.append(*kind, 1, [], payload.clone()).unwrap();
    }
    for chunk in ops.chunks(CHUNK_OVER_THRESHOLD) {
        let batch = chunk
            .iter()
            .map(|(kind, payload)| BatchEntry::new(*kind, 1, payload.clone()))
            .collect();
        batched.append_batch(batch).unwrap();
    }
    assert!(!sequential.base_order().is_empty(), "freeze must have run");
    assert_journals_identical(&sequential, &batched);

    // Shared base: freezes defer while a sibling fork keeps the base Arc
    // shared, so both forks accumulate overlay-only entries.
    let base_journal = Journal::new();
    let mut fork_a = base_journal.fork();
    let mut fork_b = base_journal.fork();
    for (kind, payload) in &ops {
        fork_a.append(*kind, 2, [], payload.clone()).unwrap();
    }
    for chunk in ops.chunks(CHUNK_OVER_THRESHOLD) {
        let batch = chunk
            .iter()
            .map(|(kind, payload)| BatchEntry::new(*kind, 2, payload.clone()))
            .collect();
        fork_b.append_batch(batch).unwrap();
    }
    assert_eq!(
        fork_a.base_order().len(),
        0,
        "shared base must not rebase during appends"
    );
    assert_journals_identical(&fork_a, &fork_b);
}

#[test]
fn invalid_payload_in_batch_applies_prefix_and_reports() {
    let good = Payload::Number(1);
    let bad = Payload::Value(CborValue::Float(f64::NAN));

    // Sequential reference: first append lands, second fails.
    let mut sequential = Journal::new();
    let expected_first = sequential
        .append(EntryKind::Outcome, 1, [], good.clone())
        .unwrap();
    assert!(sequential.append(EntryKind::Outcome, 1, [], bad).is_err());

    let mut journal = Journal::new();
    let batch = vec![
        BatchEntry::new(EntryKind::Outcome, 1, good),
        BatchEntry::new(
            EntryKind::Outcome,
            1,
            Payload::Value(CborValue::Float(f64::NAN)),
        ),
        BatchEntry::new(EntryKind::Outcome, 1, Payload::Number(3)),
    ];
    let result = journal.append_batch(batch);
    assert!(matches!(
        result,
        Err(ledger_journal::JournalError::InvalidPayload(_))
    ));
    assert_eq!(journal.len(), 1, "only the valid prefix is applied");
    assert_eq!(journal.root_hash(), sequential.root_hash());
    assert_eq!(
        journal.head_for_actor(1),
        Some(expected_first),
        "the applied prefix chains identically"
    );
}

#[test]
fn empty_batch_is_a_noop() {
    let mut journal = Journal::new();
    let first = journal
        .append(EntryKind::Outcome, 1, [], Payload::Number(1))
        .unwrap();
    let ids = journal.append_batch(Vec::new()).unwrap();
    assert!(ids.is_empty());
    assert_eq!(journal.len(), 1);
    assert_eq!(journal.head_for_actor(1), Some(first));
}

const OVERLAY_CROSSING_ENTRIES: usize = 2_500;
const CHUNK_OVER_THRESHOLD: usize = 300;
